// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpsfrnlhbjgvrjidewtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wc2ZybmxoYmpndnJqaWRld3R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3Njc3OTYsImV4cCI6MjA1NDM0Mzc5Nn0.g0vnuDDStAOqLGOraBdmsCQ29a9cSh8LzT6tOf35PpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);